# Generated by Django 5.2 on 2025-04-25 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_teacher'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
