# Generated by Django 5.2 on 2025-04-25 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_assignment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='class_assign_name',
        ),
    ]
