# Generated by Django 5.2 on 2025-04-25 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_remove_assignment_class_assign_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='class_assign',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='attendance.class'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='attendance.teacher'),
        ),
    ]
